### ISSUE TITLE
Examples to demonstrate how the logger works

### ISSUE THREAD

**Issue by symbolix** [six8/logaware#2]
Hi,

Thank you very much for creating this logging module. Could you please help me by providing a simple example regarding the usage of this module? I tried couple of things, however was not able to get it working. A simple case example would be really helpful. (All the `tox` tests are passing by the way and I am on Python 2.7). Thanks.

**Comment by six8** [comment]
What framework are you using? I can create an example for it.

**Comment by symbolix** [comment]
Hi,
Thanks for your prompt response. No particular framework. Just plain python dev with the standard modules. I would like to use your logger for some contextual information, mostly `sys.out` and `file` logging.

For example:
    
    LOG.error("This is an ERROR", error_code='0010')

outputs:

    [2016-10-06 10:38:36Z] {myApp.py:myFunc:681} - This is an ERROR <<code (0010>>

Mostly that kind of stuff, but I was not able to start since I did not know how to start :) All of that is already possible through the `logging` module, but when I looked at the code it seems to have some cool features. So I would like to give it a try and test it.

Thanks.

**Comment by six8** [comment]
I added some examples to https://github.com/six8/logaware/pull/3

**Comment by symbolix** [comment]
Hi Mike,

Thank you very much. I will have a look and try to familiarise myself with the API.

**Comment by symbolix** [comment]
Hello Again,

I have looked at the example and, as someone new the API, this still seems a bit obscure. I am trying to start fresh so here is my code:

```
import logging
import logaware
from loggers import log, custom_log, log_meta_context, meta_log
from logaware.logger import AwareLogger, LogFormatException, LogLevel, log_method_factory

log = AwareLogger()
log.info('This is an INFO message.')
```

Well, at this stage nothing happens, as it would be expected. I am trying to figure out the following:

1) How to configure and attach a `Handler`?
2) How to attach a `Formatter` to the handler?
3) What are the options to configure various context bits of information?

At this stage, the example seems to be part of the testing framework and most of the stuff is embedded into those test function. For that reason, it is still a bit hard to understand the basics as they are inside the testing context.

**Comment by six8** [comment]
Ah, you have to set up Python logging handlers. Logaware doesn't do this for you because it's app specific. 

The easiest way to get logging output to stdout is:

```
import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)8s %(name)s: %(message)s')
```

http://docs.python-guide.org/en/latest/writing/logging/ has more info about setting up log handlers.

**Comment by symbolix** [comment]
Ah, I see. It works now. So, the logging back end to it is the native logging. I get that. So when I set the `handlers` and `formatters` etc. It seems to be working. Thanks. At least this:

```
logging.basicConfig(level=logging.DEBUG, format='%(levelname)8s %(name)s: %(message)s')

custom_log.audit('Will not be logged', context='blah')
meta_log.info('Test?')
```

gives me this:

```
AUDIT __main__: This is it.
    INFO __main__: Test?
```

So how we do the cool context stuff? :)

Apologies, I am still trying to understand how this will fit in a complete logging example.

**Comment by symbolix** [comment]
So this works:

```python
#mainApp.py

import logging
import logaware
from loggers import log, custom_log, log_meta_context, meta_log
from logaware.logger import AwareLogger, LogFormatException, LogLevel, log_method_factory
import inspect

logging.basicConfig(level=logging.DEBUG, format='%(levelname)8s %(name)s: %(message)s')

# Custom level.
custom_log.audit('Will be logged', context='blah')

# Now continue with module imports as they are going to link to the logger.
from modules import mymodule

def test_me():
	custom_log.audit('Is this is a function or what?', context='blah')
	meta_log.debug('How about this?')
	custom_log.fail('This has failed!')
	meta_log.info('and this is an INFO.')

# Functions.
meta_log.info('Test?')
test_me()
mymodule.my_sub_func()
```

```python
#mymodule.py

import logging
from loggers import log, custom_log, log_meta_context, meta_log

logging.getLogger()

# Quick test.
meta_log.warning('>> This is module top level.')

# Simple function.
def my_sub_func():
	meta_log.debug('>> Module function called.')
	custom_log.fail('>> This failed again!')

# Non import guard.
if __name__ == "__main__":
	print "No loggers defined." 
```

Gives me this:

```
   AUDIT __main__: Will be logged
 WARNING modules.mymodule: >> This is module top level.
    INFO __main__: Test?
   AUDIT __main__: Is this is a function or what?
   DEBUG __main__: How about this?
    FAIL __main__: This has failed!
    INFO __main__: and this!
   DEBUG modules.mymodule: >> Module function called.
    FAIL modules.mymodule: >> This failed again!
```

I am trying to extend this example and get a bit more information in order to understand the capabilities of `logaware`.

**Comment by symbolix** [comment]
With a formatter like:

```
format='[%(asctime)-15s] __%(name)s__ {%(filename)s:%(module)s:%(funcName)s:%(lineno)s} - %(message)s'
```

I get:

```
[2016-10-07 21:21:53,280] __modules.mymodule__ {mymodule.py:mymodule:my_sub_func:11} - >> Module function called.
```

which works, however, how can I pass-in some extra information such as:

```
meta_log.debug('>> Module function called.',  event=ERR, code=0010)
```

and get:

```
[2016-10-07 21:21:53,280] __modules.mymodule__ {mymodule.py:mymodule:my_sub_func:11} -  <%ERR:0010> - >> Module function called.
```

Obviously, I can do that with the native logger by using the `extra={'event': 'NFO', 'code': '0101'}` bit. But I am trying to get a better grasp of the benefits of `logaware`.

Thanks.

**Comment by six8** [comment]
It's when you start to use meta contexts that meta becomes useful. You can use it to define meta data at the start of a request instead of with every log message. See the https://github.com/six8/logaware/pull/3/files?diff=unified#diff-a7c0d292cdfcb6ed3888aba6eaaa50bbR58 example. I think this PR has to be committed because it fixes a bug with nested contexts.

**Comment by symbolix** [comment]
I got the `example` branch. It is all fine. However, I am not familiar with the testing workflow. For that reason I cannot run the example as it is.

I am getting:
```
Traceback (most recent call last):
  File "test_examples.py", line 91, in <module>
    test_example_meta_logger()
TypeError: test_example_meta_logger() takes exactly 1 argument (0 given)
```

When I try to call `test_example_meta_logger()` obviously, cause I am not sure what the argument `lastlog_factory` is. I guess that is the issue, as a total stranger to this module and the API, it is very hard to understand the examples as they are part of the testing framework. Is it possible to create a plain example that is not inside the testing framework? Thanks for your patience.

**Comment by symbolix** [comment]
An update: I managed to isolate the example bits and it seems to be working.

```python
def test_meta_logger():

    # Context Depth (0)
    meta_log.error('User not found.')

    with log_meta_context(user='admin'):
        # Context Depth (1)
        meta_log.info('User logged in.')

        with log_meta_context(name='Bob'):
            # Context Depth (2)
            meta_log.info('User updated info.')

        # Log message will have only have meta from original context
        # Back to Context Depth (1)
        meta_log.info('User says hi.')

    # {user} will be None because the meta context has exited
    # Back to Context Depth (0)
    meta_log.info('User logged out.')
```

This gives me:

```
[2016-10-08 09:58:39,221] <__main__> {myApp:test_meta_logger:74} ERROR User not found. >> {}
[2016-10-08 09:58:39,221] <__main__> {myApp:test_meta_logger:78} INFO User logged in. >> {"user":"admin"}
[2016-10-08 09:58:39,222] <__main__> {myApp:test_meta_logger:82} INFO User updated info. >> {"name":"Bob", "user":"admin"}
[2016-10-08 09:58:39,222] <__main__> {myApp:test_meta_logger:85} INFO User says hi. >> {"user":"admin"}
[2016-10-08 09:58:39,222] <__main__> {myApp:test_meta_logger:88} INFO User logged out. >> {}
```

Now I will put together a standalone example as I would like to test couple of more things. I will let you know. Thank you very much.

**Comment by symbolix** [comment]
Just one more thing. Is it possible to have a case where the contextual information actually has an effect on the way the log message is registered? For example a custom logger level `event` that will only generate a log message in case of some arbitrary condition is met.

Let me explain this with a simple example:

```python
def test_condition_info():

    # Level (1)
    with log_meta_context(current_size=5, size_limit=9): meta_log.event('Limit event has occured.')
```

This will produce:

```
[2016-10-08 10:07:29,807] <__main__> {myApp:test_condition_info:93} (EVENT) Limit event has occured. >> {"current_size":5, "size_limit":9}
```

... and the logic is that since `current_size < size_limit` we can see the message. How ever, the following will not register inside the logs:

```
with log_meta_context(current_size=11, size_limit=9): meta_log.event('Limit event has occurred.')
```

Considering that `current_size` and `size_limit` are dynamic values, this is something I am trying to achieve. I am curious to know if this is possible or is it a feature request?

Thanks.

**Comment by symbolix** [comment]
One final thing, and I promise to wrap this issue up :) Apologies for flooding this post.

Is this the way this works?

```python
with log_meta_context(user="admin"):
    meta_log.event('User logged in.')
```

The syntax seems a bit elaborate, is it possible to do it in this way:

```
log_meta_context.bind(user="admin)
meta_log.event('User logged in.')
```

Just curious to know if it is possible with less indents and typing. Thanks.

**Comment by six8** [comment]
You can filter out log messages using [logging Filters](https://docs.python.org/2/library/logging.html#filter-objects).

```
class EventFilter(logging.Filter):
    def filter(record):
        # Return True if this message should be logged
        meta = getattr(record, 'meta', None)
        if meta.get('current_size', 0) < meta.get('size_limit', -1):
            # Only log if under size limit
            return True
        else:
            return False

root_logger = logging.getLogger()
root_logger.addFilter(EventFilter())
```

**Comment by six8** [comment]
You don't have to use the `log_meta_context` at all. It's useful for this that have nested contexts or multiple requests. For something simple like a command line program you can do:

```
meta = LogMetaManager()
meta.set_meta(user='admin')

log = MetaAwareLogger(lambda: meta.get_meta())

log.info(message)

meta.set_meta(user='bob')

log.info(message)
```

**Comment by symbolix** [comment]
Thank you very much. That was very helpfull.
