### ISSUE TITLE
How to pass extra information to the Logger?

### ISSUE THREAD

**Issue by symbolix** [six8/logaware#5]
Hello Again,

Is it possible to pass extra information together with the log message. It is a bit like the `meta` information, which I start to understand, but updated with every `log` call.

For example:

```python
log.debug('Hello World!', req=5, sup=4)
```

outputs:
```bash
[2016-11-04 18:50:10,008] [context=cli] [req(5)>sup(4)] <myApp:foo:74> INFO: Also inside __FOO?
```

I know how to pass that information to the logger, however, with `logaware`, I am not sure which bit to wrap so that I have control on the `log.record`. And about the formatting that looks like this `[req(5)>sup(4)] `, I can do that with my own Formatter, the question is how to get those into the `log.record`? 

From the example, you have provided, I know that it is possible to wrap `logaware` classes and prepare our own `Loggers`, however I am not sure how to implement that. I can see it is possible in the following example.

```
class CustomLogger(AwareLogger):
    """
    Logger with additional levels for auditing and debugging.
    """
   (...)
```

[This project](https://github.com/Dinoshauer/linie) is doing it successfully and in a simple way. But it uses a custom logging class. So if that is the case, what would be the best way to approach this issue? Do we inherit from the `AwareLogger` just like we inherit from the `logging.Logger` and simply inject into the `record` with every `log.level` call?

Thanks.

**Comment by symbolix** [comment]
I have solved this by relying on the `extra={'fruit': 'lemon'}` mechanics that are already implemented in the standard `logging` module. Almost every approach I have examined, relies on injecting data into the `extra` slot so that that information ends up in the `logging.record`. So please ignore this issue, I will close it. However I came across a potential problem, for that I will start a new issue. Thanks.

**Comment by six8** [comment]
Everything you pass as keyword arguments to a log method end up in the regular log record `extra` as `data`. So you should be able to do `record.extra['data']['req']`.
